---
apiVersion: v1
kind: Service
metadata:
  name: paas-operator
  namespace: default
  labels:
    app: paas-operator
spec:
  type: ClusterIP
  selector:
    app: paas-operator
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
