{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paas-operator.secretName" . }}
  labels:
    {{- include "paas-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretKey }}: {{ .Values.auth.apiKey | quote }}
{{- end }}
