apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "odoo-dev-sandbox.namespace" . }}
  labels:
    {{- include "odoo-dev-sandbox.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.sandbox.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    sandbox.woow.tw/branch: {{ .Values.sandbox.branch | quote }}
    sandbox.woow.tw/ttl: {{ .Values.sandbox.ttl | quote }}
    sandbox.woow.tw/mode: {{ .Values.sandbox.mode | quote }}
    sandbox.woow.tw/created: {{ now | date "2006-01-02T15:04:05Z" | quote }}
    {{- if ne .Values.sandbox.ttl "0" }}
    sandbox.woow.tw/expires: {{ now | dateModify .Values.sandbox.ttl | date "2006-01-02T15:04:05Z" | quote }}
    {{- else }}
    sandbox.woow.tw/expires: "never"
    {{- end }}
