{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-dev-sandbox.fullname" . }}-pgadmin
  namespace: {{ include "odoo-dev-sandbox.namespace" . }}
  labels:
    {{- include "odoo-dev-sandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "odoo-dev-sandbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgadmin
  template:
    metadata:
      labels:
        {{- include "odoo-dev-sandbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: "{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
          imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.defaultEmail | quote }}
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.pgadmin.defaultPassword | quote }}
          resources:
            {{- toYaml .Values.pgadmin.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-dev-sandbox.fullname" . }}-pgadmin
  namespace: {{ include "odoo-dev-sandbox.namespace" . }}
  labels:
    {{- include "odoo-dev-sandbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5050
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "odoo-dev-sandbox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
{{- end }}
