{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-dev-sandbox.secretName" . }}
  namespace: {{ include "odoo-dev-sandbox.namespace" . }}
  labels:
    {{- include "odoo-dev-sandbox.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-database: {{ include "odoo-dev-sandbox.dbName" . | b64enc | quote }}
  odoo-admin-password: {{ .Values.odoo.adminPassword | b64enc | quote }}
{{- end }}
